'use strict';
const t=require('node:test'),a=require('node:assert/strict'),E=require('../lib/execution.cjs');
const NOW=Date.parse('2026-09-23T03:00:00Z');
const start=(id='one')=>E.acquire(E.idle(),'global-main',{now:NOW,budgetMs:120000,executionId:id});
function staged(){let s=start();s=E.transition(s,s,'analyzing',{},NOW+1000);const b={batchVersion:1,batchId:'batch',taskGroup:'global-main',execution:{executionId:s.executionId,generation:s.generation},modules:[]};s=E.transition(s,s,'awaiting-publication',{batchId:b.batchId,batchHash:E.digest(b)},NOW+2000);return {s,b};}
t('all three task groups share a lease before collection',()=>{const s=start();for(const g of ['global-main','asia-session','us-session'])a.throws(()=>E.acquire(s,g,{now:NOW+5,executionId:g}),{code:'BUSY'});});
t('deadlines do not renew with phase transitions',()=>{const s=start(),n=E.transition(s,s,'analyzing',{},NOW+20000);a.equal(n.deadlineAt,s.deadlineAt);});
t('expired owner cannot move forward',()=>{const s=start();a.throws(()=>E.transition(s,s,'analyzing',{},NOW+120000),/deadline/);});
t('lease takeover fences late original worker',()=>{const s=start(),n=E.acquire(s,'asia-session',{now:NOW+120001,executionId:'two'});a.equal(n.generation,s.generation+1);a.throws(()=>E.assertOwner(n,s,NOW+120002),/obsolete/);});
t('unknown state and missing token fail closed',()=>{a.throws(()=>E.acquire({},'global-main'));a.throws(()=>E.permit(start(),{}));});
t('collection cannot jump straight to published',()=>a.throws(()=>E.transition(start(),start(),'completed',{reportId:'report',receiptHash:'hash'},NOW+1),/Illegal/));
t('complete hash-bound report required for publication',()=>{const {s,b}=staged(),p=E.transition(s,s,'publishing',{workflowRunId:123},NOW+3000);a.equal(E.permit(p,b,NOW+5000).batchId,b.batchId);a.throws(()=>E.permit(p,{...b,modules:[{}]},NOW+5000),/exact batch/);});
t('publishing lease is not stolen on expiry',()=>{const {s}=staged(),p=E.transition(s,s,'publishing',{workflowRunId:123},NOW+3000);a.throws(()=>E.acquire(p,'global-main',{now:NOW+3600000}),{code:'BUSY'});});
t('finish stores phase times and duplicate slot rejection',()=>{const {s}=staged();let p=E.transition(s,s,'publishing',{workflowRunId:123},NOW+3000);p=E.transition(p,p,'completed',{reportId:'2026-09-23-1100',receiptHash:'a'.repeat(64)},NOW+5000);a.equal(p.totalDurationMs,5000);a.equal(p.stages.length,4);a.throws(()=>E.acquire(p,'global-main',{now:NOW+6000}),/already completed/);});
t('phase payload cannot change owner, deadline or generation',()=>{const s=start(),n=E.transition(s,s,'analyzing',{generation:9,executionId:'bad',deadlineAt:'2999-01-01'},NOW+5);a.equal(n.generation,1);a.equal(n.executionId,'one');a.equal(n.deadlineAt,s.deadlineAt);});
t('concurrent CAS contenders run only one collector',async()=>{let revision=0,state=E.idle(),collected=0;const store={read:async()=>({sha:revision,state:structuredClone(state)}),cas:async(s,n)=>{await new Promise(r=>setTimeout(r,1));if(s.sha!==revision)throw new E.Conflict();state=n;revision++;return {sha:revision,state:n};}};const out=await Promise.allSettled(Array.from({length:8},(_,i)=>E.begin(store,'global-main',{now:NOW,executionId:'worker-'+i}).then(()=>collected++)));a.equal(collected,1);a.equal(out.filter(x=>x.status==='rejected').length,7);});
t('one repair per failed slot, not unlimited resubmission',()=>{let s=start();s=E.transition(s,s,'failed',{reason:'test'},NOW+1);s=E.acquire(s,'global-main',{now:NOW+2,executionId:'two'});s=E.transition(s,s,'failed',{reason:'test'},NOW+3);a.throws(()=>E.acquire(s,'global-main',{now:NOW+4}),/two attempts/);});
