'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const P=require('../lib/pipeline.cjs'),B=require('../lib/batch.cjs'),Pub=require('../lib/publication.cjs'),Control=require('../lib/control.cjs'),F=require('./fixtures.cjs');
const config=P.read(path.join(__dirname,'../config/watchlist.json')),at=Date.parse('2026-09-23T03:00:00Z');
function temporary(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gdr-execution-case-'));try{return fn(root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
function bundle(validationOnly=false){const id='isolated-integration',mods=F.producers(config,at,0,id);for(const m of Object.values(mods)){m.dataMode='production';m.validationOnly=validationOnly;m.execution.mode='scheduled-batch';}
 const report=F.reportFor(mods,at);report.reportMeta.dataMode='production';report.reportMeta.validationOnly=validationOnly;
 const synthesis={moduleVersion:1,module:'synthesis',runId:'isolated-synthesis',generatedAt:F.utc8(at+30000),dataAsOf:null,dataMode:'production',validationOnly,status:'partial',sources:[],execution:{batchId:id,mode:'scheduled-batch',role:'synthesis'},payload:{report}};
 return {batchVersion:1,batchId:id,taskGroup:'global-main',execution:{executionId:'case-worker',generation:1},modules:[...Object.values(mods),synthesis]};}
test('validation-labelled observations cannot enter production',()=>temporary(root=>{P.atomic(path.join(root,'automation/control.json'),{version:1,productionPaused:false});assert.throws(()=>B.prepareBatch(root,bundle(true),at+60000),/isolated/);assert.equal(P.read(path.join(root,'data/latest.json')),null);}));
test('unlabelled production observations cannot enter real validation root',()=>temporary(root=>{P.atomic(path.join(root,Control.VALIDATION_MARKER),{purpose:'isolated-real-data-validation',allowRealValidation:true});assert.throws(()=>B.prepareBatch(root,bundle(false),at+60000),/isolated/);}));
test('real validation root and synthetic root are distinct',()=>temporary(root=>{P.atomic(path.join(root,Control.VALIDATION_MARKER),{purpose:'isolated-real-data-validation',allowRealValidation:true});const m=F.producers(config,at).quotes;assert.ok(Control.checkMode(root,m).length);}));
test('unfenced complete production batch cannot change pointers',()=>temporary(root=>{P.atomic(path.join(root,'automation/control.json'),{version:1,productionPaused:false,executionProtocol:'lease-v1'});B.submitBatch(root,bundle());const r=B.promoteBatches(root,at+60000);assert.equal(r[0].status,'rejected');assert.match(r[0].errors[0],/permit/);assert.equal(P.read(path.join(root,'data/latest.json')),null);}));
test('old generation in a local permit rejects a complete candidate',()=>temporary(root=>{const b=bundle();P.atomic(path.join(root,'automation/control.json'),{version:1,productionPaused:false,executionProtocol:'lease-v1'});P.atomic(path.join(root,'.runtime/execution-permit.json'),{batchId:b.batchId,batchHash:P.hash(b),executionId:b.execution.executionId,generation:2});B.submitBatch(root,b);assert.equal(B.promoteBatches(root,at+60000)[0].status,'rejected');assert.equal(P.read(path.join(root,'data/latest.json')),null);}));
test('fenced batch publishes all seven modules in one local transaction',()=>temporary(root=>{const b=bundle();P.atomic(path.join(root,'automation/control.json'),{version:1,productionPaused:false,executionProtocol:'lease-v1',qualityPolicy:'content-r3'});P.atomic(path.join(root,'.runtime/execution-permit.json'),{batchId:b.batchId,batchHash:P.hash(b),...b.execution,workflowRunId:1});B.submitBatch(root,b);const r=B.promoteBatches(root,at+60000);assert.equal(r[0].status,'published',JSON.stringify(r));assert.equal(r[0].modules.length,7);}));
test('single-module route cannot bypass the execution gate',()=>temporary(root=>{const m=bundle().modules[0];P.atomic(path.join(root,'automation/control.json'),{version:1,productionPaused:false,executionProtocol:'lease-v1'});Pub.submit(root,m);const r=Pub.promote(root,at+60000);assert.equal(r[0].status,'rejected');assert.match(r[0].errors[0],/Single-module/);assert.equal(P.read(path.join(root,'data/modules/quotes.json')),null);}));
test('paused production rejects writes even with a valid-looking permit',()=>temporary(root=>{const b=bundle();P.atomic(path.join(root,'automation/control.json'),{version:1,productionPaused:true,executionProtocol:'lease-v1'});P.atomic(path.join(root,'.runtime/execution-permit.json'),{batchId:b.batchId,batchHash:P.hash(b),...b.execution});B.submitBatch(root,b);assert.equal(B.promoteBatches(root,at+60000)[0].status,'paused');assert.equal(P.read(path.join(root,'data/latest.json')),null);}));
