'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const W=require('../assets/watchlist-core.js'),P=require('../lib/pipeline.cjs'),Pub=require('../lib/publication.cjs');
const at='2026-09-22T12:00:00+08:00',now=Date.parse('2026-09-22T13:00:00+08:00');
function candidate(){return{moduleVersion:1,module:'us-equities',runId:'test-us-metadata',generatedAt:at,dataAsOf:at,status:'partial',sources:[{id:'source',url:'https://example.org/test-only',verifiedAt:at}],payload:{groups:[{id:'technology',market:'US',name:'test-only',expectedCount:null,asOf:at,currency:'USD',comparisonBasis:'previous-official-close',rows:[{instrumentId:'EQUITY:US:TEST',price:1,changePct:0,asOf:at,volumeRatio20d:null,turnoverPct:null,avgDailyValue20d:null,sourceIds:['source']}]}]}};}
function tmp(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gdr-meta-'));try{return fn(root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
test('top-level typed ranking gap statuses are metadata, not numeric observations',()=>{const m=candidate();m.payload.rankingInputGaps={volumeRatio20d:'missing',turnoverPct:'missing',avgDailyValue20d:'missing'};const before=JSON.stringify(m);assert.deepEqual(W.validate(m,'us-equities',now),[]);assert.equal(JSON.stringify(m),before);});
test('numeric strings and NaN in sector observations stay invalid with exact paths',()=>{for(const value of ['missing','12.5','',NaN,Infinity,{},[]]){const m=candidate();m.payload.groups[0].rows[0].turnoverPct=value;assert.match(W.validate(m,'us-equities',now).join('\n'),/非数值 turnoverPct.*@ \/payload\/groups\/0\/rows\/0\/turnoverPct/);}});
test('a nested metadata-like field cannot bypass numeric observation validation',()=>{const m=candidate();m.payload.groups[0].rows[0].rankingInputGaps={volumeRatio20d:'missing'};assert.match(W.validate(m,'us-equities',now).join('\n'),/非数值 volumeRatio20d/);});
test('ranking metadata schema rejects arbitrary prose, arrays, numbers and unknown states',()=>{for(const value of [null,[],1,'missing',{turnoverPct:1},{turnoverPct:'green'},{sourceIds:'missing'},{missingFields:['invented']},{heatRankingGenerated:'false'}]){const m=candidate();m.payload.rankingInputGaps=value;assert.ok(W.validate(m,'us-equities',now).length,JSON.stringify(value));}});
test('timestamp and source errors identify the exact row instead of dropping all context',()=>{const m=candidate();m.payload.groups[0].rows[0].asOf='2026-09-22';m.payload.groups[0].rows[0].sourceIds=['missing'];const errors=W.validate(m,'us-equities',now).join('\n');assert.match(errors,/\/payload\/groups\/0\/rows\/0\/asOf/);assert.match(errors,/\/payload\/groups\/0\/rows\/0\/sourceIds\/0/);});
test('actual rejected candidate only changes validation, not any financial value',()=>{const f=path.join(__dirname,'../data/inbox/us-equities/20260922T164118-acceptance-us-equities.json');if(!fs.existsSync(f))return;const m=JSON.parse(fs.readFileSync(f,'utf8')),before=JSON.stringify(m);assert.deepEqual(W.validate(m,'us-equities',Math.max(now,W.time(m.generatedAt))),[]);assert.equal(JSON.stringify(m),before);});
test('idempotent ingestion includes immutable hash needed for recoverable receipts',()=>tmp(root=>{const m=candidate();const first=P.ingest(root,m,now),second=P.ingest(root,m,now);assert.equal(second.status,'idempotent');assert.equal(second.sha256,first.sha256);assert.equal(second.sha256,P.hash(P.read(path.join(root,second.path))));}));
test('recreating a lost receipt after valid ingestion retains audit hash without rewriting run',()=>tmp(root=>{const m=candidate();P.ingest(root,m,now);const file=path.join(root,P.archivePath(m)),before=fs.readFileSync(file);Pub.submit(root,m);const receipt=Pub.promote(root,now)[0];assert.equal(receipt.status,'published');assert.equal(receipt.module.sha256,P.hash(JSON.parse(before)));assert.ok(fs.readFileSync(file).equals(before));}));

test('current published gap array and boolean metadata remains backward compatible',()=>{const m=candidate();m.payload.rankingInputGaps={missingFields:['volumeRatio20d','turnoverPct'],heatRankingGenerated:false,weakRankingGenerated:false,note:'Test-only explanatory text'};assert.deepEqual(W.validate(m,'us-equities',now),[]);});

test('recovering an obsolete receipt cannot claim the older run replaced the pointer',()=>tmp(root=>{const old=candidate();P.ingest(root,old,now);const next={...candidate(),runId:'test-us-newer',generatedAt:'2026-09-22T12:30:00+08:00'};P.ingest(root,next,now);Pub.submit(root,old);const receipt=Pub.promote(root,now)[0];assert.equal(receipt.status,'archived-older');assert.equal(P.read(path.join(root,'data/modules/us-equities.json')).runId,next.runId);assert.equal(receipt.module.sha256,P.hash(P.read(path.join(root,P.archivePath(old)))));}));
