'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const P=require('../lib/pipeline.cjs'),Pub=require('../lib/publication.cjs'),W=P.W;
const at='2026-09-22T12:00:00+08:00',now=W.time('2026-09-22T13:00:00+08:00');
const markets=['A股','港股','美股','BTC','黄金','原油'];
function report(){const r={schemaVersion:5,reportId:'2026-09-22-1200',updatedAt:'2026-09-22 12:00',reportMeta:{contractVersion:'reader-r2',moduleRefs:Object.fromEntries(W.MODULES.filter(x=>x!=='synthesis').map(role=>[role,{path:`data/runs/${role}/baseline-${role}.json`,runId:'baseline-'+role,generatedAt:'2026-09-22T11:00:00+08:00',dataAsOf:null}]))},overview:'fixture only',rolling24hSummary:'fixture only',methodology:'test',period:{to:'2026-09-22 12:00'},recentPeriod:{to:'2026-09-22 12:00'},coreAnalysis:{}};
 for(const k of ['canonicalFacts','metrics','marketCoverage','worldEvents','analysisTheses','judgmentRevisions','dataDefinitions','deepDive','evolution24h','changes','recentChanges','assets','macroEvents','news','narrativeTriggers','events','watch','sources'])r[k]=[];
 r.marketCoverage=markets.map(market=>({market}));r.deepDive=markets.map(title=>({title,analysis:'fixture, not a forecast'}));
 for(const k of ['mainTheme','expectationGap','divergence','regime','priceIn','bullCase','bullInvalidation','bearCase','bearInvalidation'])r.coreAnalysis[k]='fixture';
 r.plainLanguage={verdict:'fixture',bottomLine:'fixture',whyNow:'fixture',horizon:'fixture',confidence:'fixture',invalidation:'fixture',impacts:markets.map(asset=>({asset,effect:'unknown',reason:'fixture',takeaway:'fixture',horizon:'fixture'}))};
 r.frameworkAnalysis=[{framework:'fixture',conclusion:'fixture'}];r.frameworkSynthesis={verdict:'fixture'};r.newsroom={items:[],coverage:{}};return r;
}
function m(role='quotes',extra={}){return {moduleVersion:1,module:role,runId:'20260922T120000-'+role,generatedAt:at,dataAsOf:at,status:'partial',sources:[],payload:role==='quotes'?{items:[]}:role==='synthesis'?{report:report()}:role==='research'?{records:[],checks:[]}:{},...extra};}
function temp(fn){const d=fs.mkdtempSync(path.join(os.tmpdir(),'gdr-accept-'));try{for(const role of W.MODULES.filter(x=>x!=='synthesis')){const payload=role==='quotes'?{items:[]}:role.endsWith('equities')?{groups:[]}:role==='news'?{newsroom:{items:[]}}:role==='macro'?{canonicalFacts:[],macroEvents:[],events:[]}:{records:[],checks:[]};P.ingest(d,m(role,{runId:'baseline-'+role,generatedAt:'2026-09-22T11:00:00+08:00',dataAsOf:null,payload}),now);}return fn(d);}finally{fs.rmSync(d,{recursive:true,force:true});}}
function rec(d,role,id){return P.read(path.join(d,`data/receipts/${role}/${id}.json`));}
test('invalid synthesis is rejected without a module pointer or a fake published receipt',()=>temp(d=>{const x=m('synthesis',{payload:{reportId:'plan-only'}});Pub.submit(d,x);const rs=Pub.promote(d,now);assert.equal(rs[0].status,'rejected');assert.equal(P.read(path.join(d,'data/modules/synthesis.json')),null);assert.equal(P.read(path.join(d,'data/latest.json')),null);}));
test('publication writes complete report, immutable run, history, index and receipt',()=>temp(d=>{const x=m('synthesis');Pub.submit(d,x);const rs=Pub.promote(d,now);assert.equal(rs[0].status,'published',JSON.stringify(rs));assert.equal(fs.readFileSync(path.join(d,'data/latest.json'),'utf8'),fs.readFileSync(path.join(d,'history/2026-09-22/1200.json'),'utf8'));assert.equal(P.read(path.join(d,'data/modules/synthesis.json')).runId,x.runId);assert.equal(P.read(path.join(d,'data/history-index.json')).reports[0].reportId,x.payload.report.reportId);}));
test('history collision cannot update synthesis pointer first',()=>temp(d=>{const x=m('synthesis');P.atomic(path.join(d,'history/2026-09-22/1200.json'),{different:true});Pub.submit(d,x);assert.equal(Pub.promote(d,now)[0].status,'rejected');assert.equal(P.read(path.join(d,'data/modules/synthesis.json')),null);}));
test('disk failure rolls back every pointer and receipt but returns rejection',()=>temp(d=>{const x=m('synthesis');Pub.submit(d,x);let count=0;const rs=Pub.promote(d,now,(p,s)=>{P.atomic(p,s);if(++count===3)throw Error('simulated disk failure');});assert.equal(rs[0].status,'rejected');for(const p of ['data/modules/synthesis.json','data/latest.json','history/2026-09-22/1200.json'])assert.equal(P.read(path.join(d,p)),null);assert.equal(rec(d,'synthesis',x.runId).status,'rejected');}));
test('bad candidate does not stop a valid sibling',()=>temp(d=>{const a=m('quotes'),b=m('quotes',{runId:'20260922T120001-quotes',payload:{items:[{price:'oops'}]}});Pub.submit(d,b);Pub.submit(d,a);const rs=Pub.promote(d,now);assert.ok(rs.some(r=>r.status==='published'));assert.ok(rs.some(r=>r.status==='rejected'));assert.equal(P.read(path.join(d,'data/modules/quotes.json')).runId,a.runId);}));
test('same candidate is idempotent and cannot overwrite its published receipt',()=>temp(d=>{const a=m('quotes');const file=Pub.submit(d,a);Pub.promote(d,now);const before=P.json(rec(d,'quotes',a.runId));assert.equal(Pub.promote(d,now).length,0);fs.writeFileSync(file,JSON.stringify({...a,status:'ok'}));assert.equal(Pub.promote(d,now)[0].status,'rejected');assert.equal(P.json(rec(d,'quotes',a.runId)),before);}));
test('missing frozen dependency stays waiting and publishes after exact run arrives',()=>temp(d=>{const q=m('quotes',{generatedAt:'2026-09-22T11:59:00+08:00',dataAsOf:null,runId:'20260922T115900-quotes'}),s=m('synthesis');s.payload.report.reportMeta.moduleRefs.quotes={path:P.archivePath(q),runId:q.runId,generatedAt:q.generatedAt,dataAsOf:null};Pub.submit(d,s);assert.equal(Pub.promote(d,now)[0].status,'waiting-dependencies');Pub.submit(d,q);const rs=Pub.promote(d,now);assert.equal(rs.find(r=>r.role==='synthesis').status,'published');}));
test('frozen ref metadata cannot lie about the actual source timestamp',()=>temp(d=>{const q=m('quotes');P.ingest(d,q,now);const r=report();r.reportMeta.moduleRefs.quotes={path:P.archivePath(q),runId:q.runId,generatedAt:'2026-09-22T09:00:00+08:00'};assert.match(Pub.references(d,r,now).join(','),/时点不匹配/);}));
test('newer missing or older market row does not erase valid last-known quote',()=>{const a={price:100,asOf:at,status:'snapshot'},b={price:null,asOf:'2026-09-22T12:05:00+08:00'};assert.equal(W.chooseQuote(a,b).price,100);assert.equal(W.chooseQuote(a,b).asOf,at);assert.equal(W.chooseQuote(a,b).status,'previous');assert.equal(W.chooseQuote(a,{price:90,asOf:'2026-09-22T11:00:00+08:00'}).price,100);});
test('research no-change run preserves prior check timestamps instead of erasing audit coverage',()=>{
 const previous={sources:[],payload:{records:[],checks:[{instrumentId:'EQUITY:US:AAPL',checkedAt:'2026-09-22T10:00:00+08:00',result:'no-new-material',note:'checked'}]}};
 const incoming={sources:[],payload:{records:[],checks:[],pendingQueue:[]}};
 const r=P.mergeResearch(previous,incoming);assert.equal(r.payload.checks.length,1);assert.equal(r.payload.checks[0].checkedAt,'2026-09-22T10:00:00+08:00');assert.equal(r.payload.cacheAudit.checksRetained,1);
});
test('same research event cannot silently change document identity',()=>{const a={instrumentId:'X',eventKey:'a',documentId:'doc',documentUrl:'https://example.org/old',analysis:{conclusion:'test'}};assert.throws(()=>P.mergeResearch({sources:[],payload:{records:[a]}},{sources:[],payload:{records:[{...a,documentUrl:'https://example.org/new'}]}}),/eventKey/);});
test('old research archives without merging future cached analysis',()=>temp(d=>{const newer=m('research',{generatedAt:'2026-09-22T12:30:00+08:00',runId:'later-research',payload:{records:[{instrumentId:'X',eventKey:'a',documentId:'a',documentUrl:'https://example.org/a',analyzedAt:'2026-09-22T12:25:00+08:00',analysis:{conclusion:'test'}}],checks:[]}});P.ingest(d,newer,now);assert.equal(P.ingest(d,m('research'),now).status,'archived-older');}));
test('partial news or macro envelopes cannot masquerade as working modules',()=>{assert.ok(W.validate(m('news'),'news',now).length);assert.ok(W.validate(m('macro'),'macro',now).length);for(const role of W.MODULES)for(const payload of [null,[],true,42,'bad'])assert.doesNotThrow(()=>W.validate(m(role,{payload}),role,now));});
test('malformed quote records never crash the read-side isolator',()=>{for(const item of [null,undefined,42,[],{price:'bad'}])assert.doesNotThrow(()=>W.projectModule(m('quotes',{payload:{items:[item]}}),'quotes',now));});
test('future module is never described as freshly updated',()=>assert.equal(W.freshness(m('quotes',{generatedAt:'2999-01-01T00:00:00+08:00'}),6,now),'unknown'));
