'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const R=require('../assets/reader-core.js'),C=require('../assets/terminal-core.js'),W=require('../assets/watchlist-core.js'),D=require('../assets/display-core.js');
const at='2026-09-25T03:13:03.055+08:00',stamp=Date.parse(at);
function quote(extra={}){return {id:'CRYPTO:BTC:USD',instrumentId:'CRYPTO:BTC:USD',seriesKey:'CRYPTO:BTC:USD',label:'Bitcoin',rawValue:100,displayValue:'100',unit:'USD',scope:'Coinbase Exchange',dataStatus:'snapshot',asOf:'2026-09-25T03:00:00+08:00',sourceIds:['s'],...extra};}
function report(extra={}){return {reportId:'2026-09-25-0313',updatedAt:'2026-09-25 03:13',reportMeta:{generatedAt:at,dataMode:'production',moduleRefs:{quotes:{path:'data/runs/quotes/run-quote.json',runId:'run-quote',generatedAt:at,dataAsOf:'2026-09-25T03:00:00+08:00'}}},canonicalFacts:[quote()],sources:[{id:'s',url:'https://api.exchange.coinbase.com/products/BTC-USD/ticker'}],...extra};}
function module(extra={}){return {moduleVersion:1,module:'quotes',runId:'run-quote',generatedAt:at,dataAsOf:'2026-09-25T03:00:00+08:00',dataMode:'production',status:'partial',payload:{items:[]},sources:[],...extra};}
test('recorded quote snapshots are chart observations, not fabricated fresh samples',()=>{const r=report(),before=JSON.stringify(r);const s=R.series([r],r.updatedAt);assert.equal(s.observations,1);assert.equal(s.rows[0].kind,'price');assert.equal(s.rows[0].points[0].value,100);assert.equal(s.rows[0].points[0].dataStatus,'snapshot');assert.equal(JSON.stringify(r),before);});
test('explicit quote identity restores missing index and yield types',()=>{for(const [id,unit,kind]of[['INDEX:US:SP500','index','index'],['RATE:US10Y','%','yield'],['ENERGY:WTI','USD/bbl','price']]){const f=quote({id,instrumentId:id,seriesKey:id,unit,dataStatus:'delayed',contract:kind==='price'?'2026-11':null});assert.ok(R.normalizedId(f));assert.equal(R.chartObservation(f).valueType,kind);}});
test('retained same-time quote is deduplicated without re-dating',()=>{const r=report(),r2=report({updatedAt:'2026-09-25 04:13',reportId:'2026-09-25-0413',canonicalFacts:[quote({dataStatus:'previous',retention:{runId:'original',reason:'preserved'}})]});const result=R.series([r,r2],r2.updatedAt);assert.equal(result.observations,1);assert.equal(result.rows[0].points[0].at,Date.parse(quote().asOf));assert.equal(result.rows[0].points[0].dataStatus,'previous');});
test('quote identity never converts macro ratios or flows into price curves',()=>{for(const extra of [{id:'MACRO:US:CPI',instrumentId:'MACRO:US:CPI',seriesKey:'MACRO:US:CPI',unit:'%'},{valueType:'flow'},{unit:'%'},{displayValue:'>100'},{displayValue:'约100'}])assert.ok(R.rejectReason(quote(extra)));});
test('invalid status, reference, future time and contract guards remain intact',()=>{for(const dataStatus of ['error','invalid','stale','partial','unknown'])assert.ok(R.rejectReason(quote({dataStatus})));assert.equal(R.series([report({sources:[]})],at).observations,0);assert.equal(R.series([report({canonicalFacts:[quote({asOf:'2026-09-26T03:00:00Z'})]})],at).observations,0);assert.equal(R.normalizedId(quote({id:'ENERGY:WTI',instrumentId:'ENERGY:WTI',seriesKey:'ENERGY:WTI',unit:'USD/bbl',dataStatus:'delayed'})),null);});
test('snapshot/previous health labels are not unknown or fresh-live',()=>{const h=C.health([quote(),quote({dataStatus:'previous'})]);assert.equal(h.counts.snapshot,1);assert.equal(h.counts.previous,1);assert.equal(h.counts.unknown,0);assert.equal(h.counts.live,0);});
test('frozen real reports yield source-timed observations without mutation',()=>{const r=require('../history/2026-09-25/0313.json'),prev=require('../history/2026-09-25/0211.json'),before=JSON.stringify([r,prev]),s=R.series([prev,r],r.updatedAt);assert.ok(s.rows.some(x=>x.label==='Bitcoin'&&x.points.length===2));assert.ok(s.rows.some(x=>x.label==='标普500'));assert.equal(JSON.stringify([r,prev]),before);});
test('expired radar event is overdue, never converted to time-pending',()=>{const r=report({events:[{title:'expired',at:'2026-09-25T04:30:00+08:00'}]});const x=R.radarState(r,Date.parse('2026-09-29T10:00:00+08:00'));assert.equal(x.kind,'overdue');assert.equal(x.event.title,'expired');});
test('event beyond the report 24h horizon does not become the next radar alarm',()=>{const r=report({events:[{title:'far',at:'2026-10-02T20:30:00+08:00'}]});assert.equal(R.radarState(r,stamp).kind,'outside-window');});
test('real untimed watch and genuinely future scheduled event are distinguished',()=>{const r=report({events:[{title:'watch',at:null,timing:'时间待定'},{title:'scheduled',eventAt:'2026-09-25T04:30:00+08:00'}]});assert.equal(R.radarState(r,stamp).kind,'scheduled');r.events.pop();assert.equal(R.radarState(r,stamp).kind,'untimed');});
test('explicit unknown time cannot be overwritten by a legacy eventAt alias',()=>{assert.equal(R.eventTime({at:null,eventAt:'2026-09-25T04:30:00+08:00'}),null);});
test('event impact and summary are preserved as separate text, not substituted away',()=>{const e=R.normalizeEvent({summary:'fact',impact:'consequence',at:null});assert.equal(e.summary,'fact');assert.equal(e.impact,'consequence');});
test('synthetic/validation and history clocks freeze to the selected report',()=>{for(const mode of ['synthetic','validation'])assert.equal(R.readingClock(report(),'data/latest.json',mode,stamp+999999),C.reportTime(report()));assert.equal(R.readingClock(report(),'history/2026-09-25/0313.json','',stamp+999999),C.reportTime(report()));assert.equal(R.readingClock(report(),'data/latest.json','',stamp+999999),stamp+999999);});
test('frozen module time uses precise generatedAt rather than a truncated minute',()=>{assert.equal(W.boundModule(report(),'quotes',module()).runId,'run-quote');});
test('frozen module identity mismatch is rejected even within the correct time window',()=>{assert.throws(()=>W.boundModule(report(),'quotes',module({runId:'another-run'})),/身份|identity/);});
test('frozen module cannot be later than the selected report',()=>{const r=report();r.reportMeta.moduleRefs.quotes.generatedAt='2026-09-25T03:14:00+08:00';assert.throws(()=>W.boundModule(r,'quotes',module({generatedAt:r.reportMeta.moduleRefs.quotes.generatedAt})),/未来|晚于/);});
test('frozen ref absence and path traversal do not fall back to moving current modules',()=>{const r=report();delete r.reportMeta.moduleRefs.quotes;assert.throws(()=>W.frozenPath(r,'quotes'),/冻结/);r.reportMeta.moduleRefs.quotes={...report().reportMeta.moduleRefs.quotes,path:'data/runs/quotes/../../modules/quotes.json'};assert.throws(()=>W.frozenPath(r,'quotes'),/冻结/);});
test('frozen observation time and environment mode are checked',()=>{assert.throws(()=>W.boundModule(report(),'quotes',module({dataAsOf:'2026-09-24T03:00:00+08:00'})),/数据时点/);assert.throws(()=>W.boundModule(report(),'quotes',module({dataMode:'synthetic'})),/模式/);assert.throws(()=>W.boundModule(report(),'quotes',module({validationOnly:true})),/模式/);});
test('no-change label does not imply a completed source check',()=>{assert.doesNotMatch(D.status('no-change'),/已查|已核验/);});
