'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const W=require('../assets/watchlist-core.js'),P=require('../lib/pipeline.cjs'),{promote}=require('../scripts/promote-candidates.cjs');
const at='2026-09-22T14:00:00+08:00',now=Date.parse(at);
function quote(){return {moduleVersion:1,module:'quotes',runId:'recovery-test',generatedAt:at,dataAsOf:at,status:'partial',inputVersions:{},sources:[{id:'s',url:'https://example.com/evidence'}],payload:{items:[{instrumentId:'CRYPTO:BTC:USD',price:1,changePct:null,asOf:at,status:'snapshot',sourceIds:['s']},{instrumentId:'CRYPTO:ETH:USD',price:2,asOf:'2026-09-22',sourceIds:['s']}]}};}
test('one malformed date is isolated in read projection but strict publication still rejects it',()=>{const m=quote(),raw=JSON.stringify(m),p=W.projectModule(m,'quotes',now);assert.ok(W.validate(m,'quotes',now).length);assert.ok(p.module);assert.equal(p.module.payload.items[0].price,1);assert.equal(p.module.payload.items[1].price,null);assert.equal(p.quarantined.length,1);assert.equal(JSON.stringify(m),raw);});
test('a wrong-role envelope is not rescued by row isolation',()=>{assert.equal(W.projectModule(quote(),'research',now).module,null);});
test('a synthesis plan cannot mutate a published pointer',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gdr-recovery-'));try{const m={...quote(),module:'synthesis',payload:{reportId:'2026-09-22-1400'}};assert.throws(()=>P.ingest(root,m,now));assert.equal(fs.existsSync(path.join(root,'data/modules/synthesis.json')),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('rejected submission gets receipt while valid row later publishes with a different runId',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gdr-recovery-'));try{const bad=quote();P.atomic(path.join(root,'data/inbox/quotes/recovery-test.json'),bad);let result=promote(root,now);assert.equal(result[0].status,'rejected');assert.equal(fs.existsSync(path.join(root,'data/modules/quotes.json')),false);const good={...bad,runId:'recovery-test-fixed',payload:{items:bad.payload.items.slice(0,1)}};P.atomic(path.join(root,'data/inbox/quotes/recovery-test-fixed.json'),good);result=promote(root,now);assert.equal(result[0].status,'published');assert.equal(P.read(path.join(root,'data/modules/quotes.json')).runId,'recovery-test-fixed');assert.deepEqual(promote(root,now),[]);}finally{fs.rmSync(root,{recursive:true,force:true});}});
