#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const P=require('../lib/pipeline.cjs'),F=require('../tests/fixtures.cjs');
const source=path.resolve(__dirname,'..');
function buildDemo(destination) {
  const dest=path.resolve(destination);
  if(dest===source||source.startsWith(dest+path.sep)||['data','history','assets','config','automation','lib','scripts','tests'].some(x=>dest===path.join(source,x)||dest.startsWith(path.join(source,x)+path.sep)))throw Error('Demo destination must never replace production or source paths');
  if(fs.existsSync(dest)&&(fs.lstatSync(dest).isSymbolicLink()||(fs.readdirSync(dest).length&&!fs.existsSync(path.join(dest,'synthetic-manifest.json')))))throw Error('Refuse to replace an unmarked directory');
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'gdr-fixture-'));
  try {
    F.initialize(root);
    for(const rel of ['index.html','.nojekyll','assets','config','docs'])fs.cpSync(path.join(source,rel),path.join(root,rel),{recursive:true});
    fs.mkdirSync(path.join(root,'automation'),{recursive:true});
    P.atomic(path.join(root,'automation/control.json'),{version:1,productionPaused:true,reason:'Fixture root only'});
    const config=P.read(path.join(root,'config/watchlist.json')),batches=[];
    const end=P.W.time('2026-09-22T16:00:00+08:00');
    for(let i=0;i<7;i++)batches.push(F.writeBatch(root,config,end-(6-i)*14400000,i));
    let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('<html lang="zh-CN"','<html data-mode="synthetic" lang="zh-CN"');
    html=html.replace('<title>GDR · 市场与全球情报</title>','<title>测试数据演示 · GDR</title>');
    fs.writeFileSync(path.join(root,'index.html'),html);
    const manifest={version:1,dataMode:'synthetic',productionReady:false,label:F.LABEL,fixtureAsOf:F.utc8(end),snapshots:batches.map(b=>({batchId:b.batchId,reportId:b.reportId})),
      note:'These receipts are generated by real publication code in an isolated fixture root. They are not native scheduled executions or evidence of source accuracy.'};
    P.atomic(path.join(root,'synthetic-manifest.json'),manifest);
    fs.writeFileSync(path.join(root,'fixture-evidence.html'),'<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>人工合成测试证据</title><body><h1>测试数据，非真实行情</h1><p>本页是确定性测试样本的说明，不是新闻来源或交易数据源。</p><p>全部数值由 tests/fixtures.cjs 生成。没有任何事实真实性或自动任务完成声明。</p>'+F.PRODUCERS.map(role=>'<section id="'+role+'"><h2>'+role+'</h2><p>合成数据，仅用于校验结构、引用、历史、排名与界面。</p></section>').join('')+'<a href="./">返回测试演示</a></body></html>');
    // The standard staging code creates the same byte manifest as a production build.
    const staging=path.join(root,'.runtime','site');
    cp.execFileSync(process.execPath,[path.join(source,'scripts/stage-site.cjs'),staging],{env:{...process.env,GDR_ROOT:root,GDR_BUILD_TIME:F.utc8(end)},stdio:'pipe'});
    fs.copyFileSync(path.join(root,'synthetic-manifest.json'),path.join(staging,'synthetic-manifest.json'));
    fs.copyFileSync(path.join(root,'fixture-evidence.html'),path.join(staging,'fixture-evidence.html'));
    fs.rmSync(dest,{recursive:true,force:true});fs.cpSync(staging,dest,{recursive:true});
    return {...manifest,destination:dest,files:fs.readdirSync(dest).length};
  } finally {fs.rmSync(root,{recursive:true,force:true});}
}
if(require.main===module){try{console.log(JSON.stringify(buildDemo(process.argv[2]||path.join(source,'demo')),null,2));}catch(e){console.error(e.stack);process.exitCode=1;}}
module.exports={buildDemo};
